CREATE TABLE usuarios (
	id_usuario INT PRIMARY KEY AUTO_INCREMENT,
	nomeusuario VARCHAR(60)NOT NULL,
	email VARCHAR(60)NOT NULL,
	bloqueado CHAR(3)NOT NULL,
	senha VARCHAR(10) NOT NULL
)

CREATE TABLE CLIENTES (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(60)NOT NULL,
	CPF VARCHAR(14) NOT NULL
);

CREATE TABLE VENDEDORES (
  IDVENDEDOR INT  PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  COMISAO DECIMAL(10,2) NOT NULL
);

CREATE TABLE FABRICANTES (
  IDFABRICANTE INT  PRIMARY KEY AUTO_INCREMENT,
  RAZAOSOCIAL VARCHAR(60) NOT NULL,
  TELEFONE VARCHAR(10) NOT NULL
);

CREATE TABLE PRODUTOS (
  IDPRODUTO INT  PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(60) NOT NULL,
  UNIDADE VARCHAR(5) NOT NULL,
  PRECOVENDA DECIMAL(10,2) NOT NULL,
  IDFABRICANTE INT NOT NULL,
  FOREIGN KEY(IDFABRICANTE) REFERENCES FABRICANTES(IDFABRICANTE) 
);

CREATE TABLE PEDIDOS (
  IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
  DTVENDA DATE NOT NULL,
  IDVENDEDOR INT NOT NULL,
  FOREIGN KEY(IDVENDEDOR) REFERENCES VENDEDORES(IDVENDEDOR) ,
  IDCLIENTE INT NOT NULL,
  FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE),
  SITUACAO CHAR(10) NOT NULL
);

CREATE TABLE PEDIDOPRODUTOS (
   IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
   FOREIGN KEY(IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
   IDPRODUTO INT NOT NULL,
   FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTOS(IDPRODUTO),
   VALOR DECIMAL(10,2) NOT NULL,
   QUANTIDADE DECIMAL(10,3) NOT NULL
);

CREATE TABLE PAGAMENTOS (
   IDPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
   IDPEDIDO INT NOT NULL,
   FOREIGN KEY(IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
   FORMAPAGAMENTO VARCHAR(15) NOT NULL,
   DTVENCIMENTO DATE NOT NULL,
   VALOR DECIMAL(10,2) NOT NULL,
   DTPAGAMENTO DATE NOT NULL,
   VALORPAGO DECIMAL(10,2) NOT NULL,
   SITUACAO VARCHAR(10) NOT NULL
);


